[theme]
primaryColor = "#374E55"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F5"
textColor = "#374E55"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
